"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { formatDuration } from "@/lib/utils";
import { INTEGRATION_TOOLS, isCallTool } from "@/lib/integrations/catalog";
import { Card, Notice, fieldClass, buttonClass, secondaryClass, request } from "./ui";
import TrackerAlerts from "./TrackerAlerts";
export default function ConversationSearch({ data, reps, stages, trackers, concepts, streams, alerts, searches, admin }: { data: any; reps: any[]; stages: string[]; trackers: any[]; concepts: any[]; streams: any[]; alerts: any[]; searches: any[]; admin: boolean }) {
  const router = useRouter(); const params = useSearchParams(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showTracker, setShowTracker] = useState(false);
  const run = async (fn: () => Promise<any>) => { setError(""); setBusy(true); try { await fn(); router.refresh(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } };
  const search = (f: FormData) => { const p = new URLSearchParams(); for (const [k, v] of f) if (String(v).trim()) p.set(k, String(v).trim()); router.push(`/conversations?${p}`); };
  const paginate = (page: number) => { const p = new URLSearchParams(params); p.set("page", String(page)); router.push(`/conversations?${p}`); };
  return <div className="space-y-5"><Notice error={error} />
    <Card><form key={params.toString()} onSubmit={e => { e.preventDefault(); search(new FormData(e.currentTarget)); }} className="space-y-3">
      <label className="block text-sm space-y-1">Search words, people, or companies<input className={fieldClass} name="q" defaultValue={params.get("q") || ""} placeholder="Search all transcripts…" maxLength={200} /></label>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        <label className="text-xs space-y-1">Rep<select name="repId" className={fieldClass} defaultValue={params.get("repId") || ""}><option value="">All accessible reps</option>{reps.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
        <label className="text-xs space-y-1">Call stage<select name="stage" className={fieldClass} defaultValue={params.get("stage") || ""}><option value="">All stages</option>{stages.map(s => <option key={s}>{s}</option>)}</select></label>
        <label className="text-xs space-y-1">Source<select name="source" className={fieldClass} defaultValue={params.get("source") || ""}><option value="">All sources</option><option value="upload">Upload / pasted transcript</option>{INTEGRATION_TOOLS.filter(t => isCallTool(t.id)).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
        <label className="text-xs space-y-1">From<input type="date" name="from" className={fieldClass} defaultValue={params.get("from") || ""} /></label><label className="text-xs space-y-1">Through<input type="date" name="to" className={fieldClass} defaultValue={params.get("to") || ""} /></label>
        <label className="text-xs space-y-1">Manager review<select name="reviewed" className={fieldClass} defaultValue={params.get("reviewed") || ""}><option value="">Any review status</option><option value="yes">Reviewed</option><option value="no">Needs review</option></select></label>
        <label className="text-xs space-y-1">Keyword tracker<select name="tracker" className={fieldClass} defaultValue={params.get("tracker") || ""}><option value="">All topics</option>{trackers.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
        <label className="text-xs space-y-1">Concept tracker<select name="aiTracker" className={fieldClass} defaultValue={params.get("aiTracker") || ""}><option value="">All concepts</option>{concepts.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
      </div><div className="flex flex-wrap gap-2"><button className={buttonClass}>Search</button><Link href="/conversations" className={secondaryClass}>Clear filters</Link>{admin && <button type="button" className={secondaryClass} onClick={() => setShowTracker(!showTracker)}>Manage trackers</button>}</div>
    </form></Card>
    <Card title="Saved searches"><div className="flex flex-wrap gap-2">{searches.map(s => <div key={s.id} className="flex items-center gap-1"><Link className={secondaryClass} href={`/conversations?${new URLSearchParams(s.filters)}`}>{s.name}</Link><button disabled={busy} className="text-[#86868b] px-1" aria-label={`Delete ${s.name}`} onClick={() => run(() => request("/api/searches", { id: s.id }, "DELETE"))}>×</button></div>)}</div><form className="flex gap-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => request("/api/searches", { name: f.get("name"), filters: Object.fromEntries(params) })); e.currentTarget.reset(); }}><input name="name" required className={fieldClass} maxLength={200} placeholder="Name this search" aria-label="Saved search name" /><button disabled={busy} className={secondaryClass}>Save current filters</button></form></Card>
    <TrackerAlerts admin={admin} open={showTracker} concepts={concepts} trackers={trackers} streams={streams} alerts={alerts} busy={busy} run={run} />
    {showTracker && admin && <Card title="Keyword trackers"><p className="text-xs text-[#6e6e73]">Match any of your words or phrases in a transcript. Matches link to the exact turn.</p>{trackers.map(t => <div key={t.id} className="flex justify-between text-sm"><span>{t.name} · <span className="text-[#86868b]">{t.keywords.join(", ")}</span></span><button disabled={busy} className="text-red-600" onClick={() => run(() => request("/api/trackers", { id: t.id }, "DELETE"))}>Delete</button></div>)}<form className="grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => request("/api/trackers", { name: f.get("name"), keywords: f.get("keywords") })); e.currentTarget.reset(); }}><label className="text-xs space-y-1">Tracker name<input name="name" required className={fieldClass} placeholder="Competitors" /></label><label className="text-xs space-y-1">Comma-separated words or phrases<input name="keywords" required className={fieldClass} placeholder="Gong, Chorus, competitor" /></label><button disabled={busy} className={buttonClass}>Add tracker</button></form></Card>}
    <div className="flex items-center justify-between"><h2 className="font-semibold">{data.total} conversation{data.total === 1 ? "" : "s"}</h2><Link href="/library" className="text-sm text-[#007AFF]">Open clip library →</Link></div>
    <div className="space-y-3">{data.rows.map((c: any) => <Link href={`/calls/${c.id}`} key={c.id} className="block rounded-xl border border-black/[.08] bg-white p-5 hover:border-blue-300 transition"><div className="flex justify-between gap-3"><div><h3 className="font-medium text-[#1d1d1f]">{c.title || `${c.company || c.prospectName} · ${c.stage}`}</h3><p className="text-xs text-[#6e6e73] mt-1">{c.repName} · {c.prospectName} · {formatDuration(c.duration)} · {new Date(c.createdAt).toLocaleDateString()}</p></div><span className="text-xs text-[#007AFF]">{c.reviewedAt ? "Reviewed" : "Needs review"}</span></div><p className="mt-3 text-sm text-[#6e6e73] line-clamp-2">{c.snippet}</p><div className="flex gap-2 mt-3 text-xs text-[#86868b]"><span>{c.source || "upload"}</span><span>· {c.outcome}</span><span>· {c.status}</span></div></Link>)}</div>
    {!data.rows.length && <Card><p className="text-sm text-[#6e6e73]">No conversations match these filters. Upload a call or connect a call tool to start your library.</p></Card>}
    <div className="flex justify-between items-center"><button className={secondaryClass} disabled={data.page <= 1} onClick={() => paginate(data.page - 1)}>Previous</button><span className="text-xs text-[#6e6e73]">Page {data.page} of {Math.max(1, Math.ceil(data.total / data.pageSize))}</span><button className={secondaryClass} disabled={data.page * data.pageSize >= data.total} onClick={() => paginate(data.page + 1)}>Next</button></div>
  </div>;
}
