"use client";
import CallIntegrationActions from "./CallIntegrationActions";
import CallProviderInsights from "./CallProviderInsights";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { apiPath, formatDuration } from "@/lib/utils";
import { Card, Notice, fieldClass, buttonClass, secondaryClass, request } from "./ui";

function Topics({ data, jump }: { data: any; jump: (s: number) => void }) {
  const concepts = data.conceptTrackers || [];
  const keywords = data.trackers || [];
  if (!concepts.length && !keywords.length) return <Card title="Tracked topics"><p className="text-sm text-[#86868b]">No tracker matches in this call. Add keyword or concept trackers in Conversations.</p></Card>;
  return <Card title="Tracked topics">
    {concepts.map((t: any) => <div key={t.id} className="space-y-2"><h3 className="text-sm font-medium">{t.name} · {t.hits.length} moments</h3><p className="text-xs text-[#6e6e73]">{t.concept}</p>{t.hits.slice(0, 30).map((h: any, i: number) => <button key={i} className="block w-full text-left rounded-lg bg-[#F5F5F7] p-3 hover:bg-blue-50" onClick={() => jump(h.start)}><span className="text-xs text-[#007AFF]">{formatDuration(h.start)}{h.timing === "estimated" && " (estimated)"} · {h.speaker}</span><p className="text-sm mt-1">{h.quote}</p>{h.reason && <p className="text-xs text-[#86868b] mt-1">{h.reason}</p>}</button>)}</div>)}
    {keywords.map((t: any) => <div key={t.id} className="space-y-2"><h3 className="text-sm font-medium">{t.name} · {t.hits.length} turns</h3>{t.hits.slice(0, 30).map((h: any, i: number) => <button key={i} className="block w-full text-left rounded-lg bg-[#F5F5F7] p-3 hover:bg-blue-50" onClick={() => jump(h.start)}><span className="text-xs text-[#007AFF]">{formatDuration(h.start)}{h.timing === "estimated" && " (estimated)"} · {h.speaker} · {h.terms.join(", ")}</span><p className="text-sm mt-1">{h.text}</p></button>)}</div>)}
  </Card>;
}

export default function ConversationWorkspace({ callId, duration, initial, admin, viewerId, metrics, deals }: { callId: string; duration: number; initial: any; admin: boolean; viewerId: string; metrics: { key: string; label: string; score?: number }[]; deals: { id: string; name: string; stage: string | null }[] }) {
  const router = useRouter(); const [data, setData] = useState(initial); const [tab, setTab] = useState("Overview"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const mutate = async (body: any) => { setBusy(true); setError(""); setMessage(""); try { const next = await request(`/api/conversations/${callId}`, body); setData(next); if (["override", "removeOverride"].includes(body.action)) router.refresh(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } };
  const jump = (s: number, end?: number) => { window.location.hash = `t-${Math.round(s)}${end ? `-${Math.round(end)}` : ""}`; };
  return <section className="space-y-4" aria-label="Conversation workspace"><div className="flex flex-wrap gap-2 border-b border-black/10 pb-3">{["Overview", "Topics", "Comments", "Clips", "Review"].map(t => <button key={t} className={tab === t ? buttonClass : secondaryClass} onClick={() => setTab(t)}>{t}{t === "Comments" && data.comments.length ? ` (${data.comments.length})` : ""}</button>)}</div><Notice error={error} message={message} />
    {tab === "Overview" && <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Conversation context"><h3 className="text-sm font-medium">{data.title}</h3><p className="text-xs text-[#86868b]">Source: {data.source} · {data.reviewedAt ? `Reviewed by ${data.reviewedBy}` : "Awaiting manager review"}</p>{data.recordingPageUrl && <a className={secondaryClass + " inline-block"} href={data.recordingPageUrl} target="_blank" rel="noreferrer">Open source recording ↗</a>}{data.participants.length > 0 && <div className="text-xs space-y-1">{data.participants.map((p: any,i: number) => <p key={i}>{p.name} {p.email && `(${p.email})`} {p.external && "· External"}</p>)}</div>}{data.summary && <p className="whitespace-pre-wrap text-sm text-[#6e6e73] max-h-80 overflow-auto">{data.summary}</p>}<div className="flex gap-3 text-xs">{["json", "vtt", "srt"].map(f => <a key={f} className="text-[#007AFF]" href={apiPath(`/api/conversations/${callId}?export=${f}`)}>Export {f.toUpperCase()}</a>)}</div></Card>
      {data.meetings?.length > 0 && <Card title="Matched meetings">{data.meetings.map((meeting: any) => <div key={meeting.id} className="space-y-1 text-sm"><strong>{meeting.title}</strong><p className="text-xs text-[#86868b]">{new Date(meeting.startAt).toLocaleString()} · {meeting.provider}</p><p className="text-xs text-[#6e6e73]">{meeting.participants.map((p: any) => p.name || p.email).join(", ")}</p>{meeting.sourceUrl && <a href={meeting.sourceUrl} target="_blank" rel="noreferrer" className="text-xs text-[#007AFF]">Open meeting ↗</a>}</div>)}</Card>}
      {data.providerInsights && <CallProviderInsights insights={data.providerInsights} jump={jump} />}
      {admin && <CallIntegrationActions callId={callId} linked={data.linked} clips={data.clips} />}
      <Card title="Speaker activity"><p className="text-xs text-[#6e6e73]">Share of transcript words and questions. This measures the written transcript, so it does not measure speaking time.</p>{data.stats.map((s: any) => <div key={s.name} className="space-y-1"><div className="flex justify-between text-sm"><span>{s.name}</span><span>{s.share}% · {s.questions} questions</span></div><div className="h-2 rounded-full bg-[#F5F5F7]"><div className="h-full bg-[#007AFF] rounded-full" style={{ width: `${s.share}%` }} /></div></div>)}</Card>
      <Card title="Action items">{data.actionItems.map((a: any) => <label key={a.id} className="flex gap-2 items-start text-sm"><input type="checkbox" className="mt-1" disabled={busy} checked={a.completed} onChange={e => mutate({ action: "toggleAction", id: a.id, completed: e.target.checked })} /><span className={a.completed ? "line-through text-[#86868b]" : ""}>{a.description}{a.assignee && <span className="block text-xs text-[#86868b]">{a.assignee}</span>}</span></label>)}{!data.actionItems.length && <p className="text-xs text-[#86868b]">No next steps captured yet.</p>}<form className="space-y-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); mutate({ action: "addAction", description: f.get("description"), assignee: f.get("assignee") }); e.currentTarget.reset(); }}><input className={fieldClass} name="description" required maxLength={1000} aria-label="Action item" placeholder="Add a next step" /><input className={fieldClass} name="assignee" maxLength={200} aria-label="Assignee" placeholder="Assignee (optional)" /><button disabled={busy} className={secondaryClass}>Add action item</button></form></Card>
      {admin && <Card title="CRM context">{data.linked.map((r: any) => <div key={r.id} className="flex justify-between text-sm"><div><span className="text-xs text-[#86868b]">{r.kind} · </span>{r.name}{r.stage && <span className="block text-xs">{r.stage} {r.amount && `· ${r.amount} ${r.currency || ""}`}</span>}</div>{r.kind === "deal" && <button disabled={busy} className="text-xs text-red-600" onClick={() => mutate({ action: "linkDeal", id: r.id, remove: true })}>Unlink</button>}</div>)}<form className="flex gap-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); mutate({ action: "linkDeal", id: f.get("id") }); }}><select required name="id" className={fieldClass} defaultValue=""><option value="" disabled>Link a CRM deal</option>{deals.map(d => <option key={d.id} value={d.id}>{d.name} · {d.stage}</option>)}</select><button disabled={busy || !deals.length} className={secondaryClass}>Link</button></form><Link href="/deals" className="inline-block text-xs text-[#007AFF]">Open pipeline →</Link></Card>}
    </div>}
    {tab === "Topics" && <Topics data={data} jump={jump} />}
    {tab === "Comments" && <Card title="Call comments">{data.comments.map((c: any) => <div key={c.id} className="rounded-lg bg-[#F5F5F7] p-3"><div className="flex justify-between text-xs text-[#86868b]"><span>{c.authorName} · {new Date(c.createdAt).toLocaleString()}</span>{c.timestampSeconds != null && <button className="text-[#007AFF]" onClick={() => jump(c.timestampSeconds)}>{formatDuration(c.timestampSeconds)}</button>}</div><p className="text-sm whitespace-pre-wrap mt-2">{c.body}</p>{(admin || c.authorId === viewerId) && <button disabled={busy} className="text-xs text-red-600 mt-2" onClick={() => mutate({ action: "deleteComment", id: c.id })}>Delete</button>}</div>)}<form className="space-y-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); mutate({ action: "comment", body: f.get("body"), timestamp: f.get("timestamp") }); e.currentTarget.reset(); }}><textarea name="body" required maxLength={4000} className={fieldClass} rows={3} aria-label="Comment" placeholder="Add coaching feedback…" /><label className="block text-xs space-y-1">Timestamp in seconds (optional)<input type="number" name="timestamp" min={0} max={duration} className={fieldClass} /></label><button disabled={busy} className={buttonClass}>Add comment</button></form></Card>}
    {tab === "Clips" && <Card title="Reusable moments"><p className="text-xs text-[#6e6e73]">Save a range in the recording or transcript to a coaching collection. Access follows the original call.</p>{data.clips.map((c: any) => <div key={c.id} className="flex justify-between text-sm bg-[#F5F5F7] p-3 rounded-lg"><button className="text-left" onClick={() => jump(c.startSeconds, c.endSeconds)}><strong>{c.title}</strong><span className="block text-xs text-[#007AFF]">{c.collection} · {formatDuration(c.startSeconds)}–{formatDuration(c.endSeconds)}</span></button>{(admin || c.createdBy === viewerId) && <button disabled={busy} className="text-xs text-red-600" onClick={() => mutate({ action: "deleteClip", id: c.id })}>Delete</button>}</div>)}<form className="grid grid-cols-2 gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); mutate({ action: "clip", title: f.get("title"), collection: f.get("collection"), start: f.get("start"), end: f.get("end") }); e.currentTarget.reset(); }}><label className="text-xs space-y-1">Clip title<input name="title" required className={fieldClass} maxLength={200} /></label><label className="text-xs space-y-1">Collection<input name="collection" defaultValue="Examples" required className={fieldClass} maxLength={100} /></label><label className="text-xs space-y-1">Start (seconds)<input name="start" type="number" min={0} max={duration} required className={fieldClass} /></label><label className="text-xs space-y-1">End (seconds)<input name="end" type="number" min={1} max={duration} required className={fieldClass} /></label><button disabled={busy} className={buttonClass}>Save clip</button><Link href="/library" className={secondaryClass + " text-center"}>Clip library</Link></form></Card>}
    {tab === "Review" && <Card title="Manager review"><p className="text-sm text-[#6e6e73]">{data.reviewedAt ? `Reviewed by ${data.reviewedBy} on ${new Date(data.reviewedAt).toLocaleDateString()}` : "This call has not been reviewed."}</p>{admin && <button disabled={busy} className={secondaryClass} onClick={() => mutate({ action: "review", reviewed: !data.reviewedAt })}>{data.reviewedAt ? "Mark as needs review" : "Mark reviewed"}</button>}
      {data.overrides.map((o: any) => <div key={o.id} className="rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm"><div className="flex justify-between"><strong>{metrics.find(m => m.key === o.metricKey)?.label || o.metricKey} · {o.score}/10</strong>{admin && <button disabled={busy} className="text-xs text-[#007AFF]" onClick={() => mutate({ action: "removeOverride", metricKey: o.metricKey })}>Restore AI score</button>}</div><p>{o.reason}</p><p className="mt-1 text-xs text-[#86868b]">{o.authorName} · Human correction</p></div>)}
      {admin && metrics.length > 0 && <form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); mutate({ action: "override", metricKey: f.get("metricKey"), score: f.get("score"), reason: f.get("reason") }); }}><h3 className="text-sm font-medium">Correct a scorecard metric</h3><div className="grid grid-cols-2 gap-3"><label className="text-xs space-y-1">Metric<select name="metricKey" className={fieldClass}>{metrics.map(m => <option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label className="text-xs space-y-1">Score (1–10)<input name="score" type="number" min={1} max={10} required className={fieldClass} /></label></div><label className="block text-xs space-y-1">Reason<textarea name="reason" required maxLength={2000} className={fieldClass} rows={2} /></label><button disabled={busy} className={buttonClass}>Save correction</button></form>}
      {admin && <div className="border-t border-black/10 pt-4"><button disabled={busy} className="text-sm text-red-600" onClick={async () => { if (!confirm("Permanently delete this call, its recording, evaluation, comments, and clips?")) return; setBusy(true); try { await request(`/api/conversations/${callId}`, {}, "DELETE"); router.push("/conversations"); router.refresh(); } catch(e) { setError((e as Error).message); setBusy(false); } }}>Delete conversation permanently</button></div>}
    </Card>}
  </section>;
}
