"use client";
import { useState } from "react";
import Link from "next/link";
import { Card, fieldClass } from "./ui";
export default function DealPipeline({ data }: { data: any }) {
  const [q,setQ] = useState(""); const [status,setStatus] = useState("open"); const [stage,setStage] = useState(""); const [risk,setRisk] = useState(false);
  const deals = data.deals.filter((d: any) => (!q || d.name.toLowerCase().includes(q.toLowerCase()) || d.associated.some((a: any) => a.name.toLowerCase().includes(q.toLowerCase()))) && (status === "all" || (status === "closed" ? d.closed : !d.closed)) && (!stage || stage === d.stage) && (!risk || d.risks.length));
  return <div className="space-y-5"><div className="grid sm:grid-cols-3 gap-4"><Card title="Open pipeline">{Object.entries(data.totals).map(([currency,total]) => <p key={currency} className="text-2xl font-semibold">{Number(total).toLocaleString()} <span className="text-sm font-normal">{currency}</span></p>)}{!Object.keys(data.totals).length && <p className="text-sm text-[#86868b]">No open amounts synced.</p>}</Card><Card title="CRM coverage"><p className="text-2xl font-semibold">{data.companies} <span className="text-sm font-normal">companies</span></p><p className="text-sm text-[#6e6e73]">{data.contacts} contacts · {data.deals.length} deals</p></Card><Card title="Activity flags"><p className="text-2xl font-semibold">{data.deals.filter((d: any) => d.risks.length).length}</p><p className="text-xs text-[#6e6e73]">Based on linked calls, close dates, and open action items.</p></Card></div>
    <Card><div className="grid sm:grid-cols-3 gap-3"><input className={fieldClass} aria-label="Search deals" placeholder="Find a deal or account" value={q} onChange={e => setQ(e.target.value)} /><select className={fieldClass} aria-label="Deal status" value={status} onChange={e => setStatus(e.target.value)}><option value="open">Open deals</option><option value="closed">Closed deals</option><option value="all">All deals</option></select><select className={fieldClass} aria-label="Deal stage" value={stage} onChange={e => setStage(e.target.value)}><option value="">All pipeline stages</option>{[...new Set(data.deals.map((d: any) => d.stage).filter(Boolean))].map(s => <option key={String(s)}>{String(s)}</option>)}</select></div><label className="text-sm flex gap-2"><input type="checkbox" checked={risk} onChange={e => setRisk(e.target.checked)} />Only deals with activity flags</label></Card>
    {!data.deals.length && <Card><p className="text-sm text-[#6e6e73]">Connect a CRM to import your pipeline.</p><Link href="/admin/integrations" className="text-sm text-[#007AFF]">Connect a CRM →</Link></Card>}
    {deals.map((d: any) => <Card key={d.id}><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{d.name}</h2><p className="text-xs text-[#86868b] mt-1">{d.stage || "No stage"} · {d.closed ? d.won ? "Won" : "Closed" : "Open"}{d.closeDate && ` · Closes ${new Date(d.closeDate).toLocaleDateString()}`}</p></div><p className="font-semibold">{d.amount ? `${Number(d.amount).toLocaleString()} ${d.currency || ""}` : "Amount unavailable"}</p></div><div className="flex flex-wrap gap-2">{d.risks.map((r: string) => <span key={r} className="rounded-full bg-amber-50 text-amber-800 px-2 py-1 text-xs">{r}</span>)}</div>{d.associated.length > 0 && <p className="text-xs text-[#6e6e73]">{d.associated.map((a: any) => `${a.name}${a.email ? ` (${a.email})` : ""}`).join(" · ")}</p>}<div className="space-y-2">{d.linkedCalls.map((c: any) => <Link key={c.id} href={`/calls/${c.id}`} className="block rounded-lg bg-[#F5F5F7] p-3 text-sm text-[#007AFF]">{c.title} <span className="text-xs text-[#86868b]">· {new Date(c.createdAt).toLocaleDateString()}</span></Link>)}{!d.linkedCalls.length && <p className="text-xs text-[#86868b]">Link a conversation from its CRM context panel.</p>}</div><p className="text-xs text-[#86868b]">{d.openActions} open action items · Synced {new Date(d.syncedAt).toLocaleString()}</p></Card>)}
  </div>;
}
