"use client";
import { useState } from "react";
import Link from "next/link";
import type { crmOverview } from "@/lib/revenue/crm";
import { amountValue, CATEGORY_LABELS, FORECAST_CATEGORIES, MEDDICC, type ForecastCategory } from "@/lib/revenue/forecast-model";
import { Card, fieldClass, secondaryClass } from "./ui";
export default function DealPipeline({ data }: { data: Awaited<ReturnType<typeof crmOverview>> }) {
  const [q, setQ] = useState(""); const [status, setStatus] = useState("open"); const [stage, setStage] = useState("");
  const [risk, setRisk] = useState(false); const [owner, setOwner] = useState(""); const [category, setCategory] = useState("");
  const deals = data.deals.filter(d => (!q || d.name.toLowerCase().includes(q.toLowerCase()) || d.associated.some(a => a.name.toLowerCase().includes(q.toLowerCase())))
    && (status === "all" || (status === "closed" ? d.closed : !d.closed)) && (!stage || stage === d.stage)
    && (!risk || d.risks.length) && (!owner || (d.owner || "Unassigned") === owner) && (!category || (!d.closed && d.review.category === category)));
  return <div className="space-y-5">
    <div className="flex flex-wrap justify-between items-center gap-3"><p className="text-sm text-[#6e6e73]">{deals.length} matching deals</p><Link href="/forecast" className={secondaryClass}>Open revenue forecast →</Link></div>
    <div className="grid sm:grid-cols-3 gap-4"><Card title="Open pipeline">{Object.entries(data.totals).map(([currency, total]) => <p key={currency} className="text-2xl font-semibold">{Number(total).toLocaleString()} <span className="text-sm font-normal">{currency}</span></p>)}{!Object.keys(data.totals).length && <p className="text-sm text-[#86868b]">No open amounts synced.</p>}</Card><Card title="CRM coverage"><p className="text-2xl font-semibold">{data.companies} <span className="text-sm font-normal">companies</span></p><p className="text-sm text-[#6e6e73]">{data.contacts} contacts · {data.deals.filter(d => !d.closed && d.review.revision > 0).length} open deals reviewed</p></Card><Card title="Activity flags"><p className="text-2xl font-semibold">{data.deals.filter(d => d.risks.length).length}</p><p className="text-xs text-[#6e6e73]">Based on linked calls, close dates, and next steps.</p></Card></div>
    <Card><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3"><input className={fieldClass} aria-label="Search deals" placeholder="Find a deal or account" value={q} onChange={e => setQ(e.target.value)} /><select className={fieldClass} aria-label="Deal status" value={status} onChange={e => setStatus(e.target.value)}><option value="open">Open deals</option><option value="closed">Closed deals</option><option value="all">All deals</option></select><select className={fieldClass} aria-label="Deal stage" value={stage} onChange={e => setStage(e.target.value)}><option value="">All pipeline stages</option>{[...new Set(data.deals.map(d => d.stage).filter(Boolean))].map(s => <option key={s!}>{s}</option>)}</select><select className={fieldClass} aria-label="Deal owner" value={owner} onChange={e => setOwner(e.target.value)}><option value="">All CRM owners</option>{[...new Set(data.deals.map(d => d.owner || "Unassigned"))].sort().map(o => <option key={o}>{o}</option>)}</select><select className={fieldClass} aria-label="Forecast category" value={category} onChange={e => setCategory(e.target.value)}><option value="">All forecast categories</option>{FORECAST_CATEGORIES.map(c => <option key={c} value={c}>{CATEGORY_LABELS[c]}</option>)}</select></div><label className="text-sm flex gap-2"><input type="checkbox" checked={risk} onChange={e => setRisk(e.target.checked)} />Only deals with activity flags</label></Card>
    {!data.deals.length && <Card><p className="text-sm text-[#6e6e73]">Connect a CRM to import your pipeline.</p><Link href="/admin/integrations" className="text-sm text-[#007AFF]">Connect a CRM →</Link></Card>}
    {!!data.deals.length && !deals.length && <Card><p className="text-sm text-[#6e6e73]">No deals match these filters.</p></Card>}
    {deals.map(d => <Card key={d.id}><div className="flex justify-between gap-3"><div><Link href={`/deals/${encodeURIComponent(d.id)}`} className="font-semibold text-[#007AFF]">{d.name} →</Link><p className="text-xs text-[#86868b] mt-1">{d.stage || "No stage"} · {d.owner || "Unassigned"} · {d.closed ? d.won ? "Won" : "Closed" : "Open"}{d.closeDate && ` · Closes ${d.closeDate.slice(0, 10)}`}</p></div><p className="font-semibold">{amountValue(d.amount) !== null ? `${amountValue(d.amount)!.toLocaleString()} ${d.currency || ""}` : "Amount unavailable"}</p></div>
      <div className="flex flex-wrap gap-2">{!d.closed && <span className="rounded-full bg-blue-50 text-blue-800 px-2 py-1 text-xs">{CATEGORY_LABELS[d.review.category as ForecastCategory]}{d.review.probability !== null && ` · ${d.review.probability}% estimated`}</span>}{d.risks.map(r => <span key={r} className="rounded-full bg-amber-50 text-amber-800 px-2 py-1 text-xs">{r}</span>)}</div>
      <p className="text-xs text-[#6e6e73]">MEDDICC: {MEDDICC.filter(({ key }) => d.review.playbook[key].status === "confirmed").length}/{MEDDICC.length} confirmed · {d.linkedCalls.length} conversations · {d.openActions} open call actions</p>
      {d.review.nextStep && <p className="text-sm text-[#6e6e73]">Next step: {d.review.nextStep}{d.review.nextStepDate && ` · Due ${d.review.nextStepDate}`}</p>}
      {d.associated.length > 0 && <p className="text-xs text-[#6e6e73]">{d.associated.map(a => `${a.name}${a.email ? ` (${a.email})` : ""}`).join(" · ")}</p>}
      <div className="space-y-2">{d.linkedCalls.slice(0, 3).map(c => <Link key={c.id} href={`/calls/${encodeURIComponent(c.id)}`} className="block rounded-lg bg-[#F5F5F7] p-3 text-sm text-[#007AFF]">{c.title} <span className="text-xs text-[#86868b]">· {new Date(c.createdAt).toLocaleDateString()}</span></Link>)}{!d.linkedCalls.length && <p className="text-xs text-[#86868b]">Link a conversation from its CRM context panel.</p>}</div>
      <div className="flex flex-wrap justify-between gap-2"><Link href={`/deals/${encodeURIComponent(d.id)}`} className="text-sm text-[#007AFF]">Review deal & qualification →</Link><p className="text-xs text-[#86868b]">Synced {new Date(d.syncedAt).toLocaleString()}</p></div>
    </Card>)}
  </div>;
}
