/**
 * Rebuild src/data/peeringdb-networks.ts from the public PeeringDB API.
 *
 *   npm run refresh-asns
 *
 * PeeringDB is queried read-only. The snapshot stores an ASN to network-type
 * classification, not organization names or contact data.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { networkTypeFromPeeringDb } from "../src/peeringdb.ts";
import type { NetworkType } from "../src/types.ts";

const UA = "visitor-company/0.1.0 (asn classification refresh; company-level only)";
const PAGE = 2000;
const OUTPUT = resolve(dirname(fileURLToPath(import.meta.url)), "../src/data/peeringdb-networks.ts");

const STORED_TYPES = [
  "enterprise",
  "educational",
  "government",
  "nonprofit",
  "isp",
  "transit",
  "content",
] as const satisfies readonly NetworkType[];

interface NetRow {
  asn?: number;
  info_type?: string | null;
  info_types?: string[] | null;
}

async function fetchPage(skip: number): Promise<NetRow[]> {
  const url = new URL("https://www.peeringdb.com/api/net");
  url.searchParams.set("limit", String(PAGE));
  url.searchParams.set("skip", String(skip));
  url.searchParams.set("depth", "0");
  url.searchParams.set("fields", "asn,info_type,info_types");

  let lastStatus = 0;
  for (let attempt = 0; attempt < 8; attempt += 1) {
    const response = await fetch(url, {
      headers: { accept: "application/json", "user-agent": UA },
    });
    lastStatus = response.status;
    if (response.status === 429 || response.status >= 500) {
      const retryAfter = Number(response.headers.get("retry-after"));
      const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 15000 * (attempt + 1);
      console.error(`PeeringDB ${response.status} at skip=${skip}, waiting ${waitMs}ms`);
      await sleep(waitMs);
      continue;
    }
    if (!response.ok) {
      throw new Error(`PeeringDB responded ${response.status} at skip=${skip}`);
    }
    const body = (await response.json()) as { data?: NetRow[] };
    return body.data ?? [];
  }
  throw new Error(`PeeringDB kept failing (${lastStatus}) at skip=${skip}`);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolveSleep) => {
    setTimeout(resolveSleep, ms);
  });
}

function emit(grouped: Map<NetworkType, number[]>): string {
  const counts: string[] = [];
  const blocks: string[] = [];
  for (const type of STORED_TYPES) {
    const asns = grouped.get(type) ?? [];
    asns.sort((a, b) => a - b);
    counts.push(`  ${type}: ${asns.length},`);
    const lines: string[] = [];
    for (let i = 0; i < asns.length; i += 20) {
      lines.push(`    ${asns.slice(i, i + 20).join(", ")},`);
    }
    blocks.push(`  ${type}: [\n${lines.join("\n")}\n  ],`);
  }

  return `/** Generated by scripts/refresh-peeringdb.ts. Do not edit by hand. */
/** Network types derived from PeeringDB (https://www.peeringdb.com/). */
export const peeringDbGeneratedAt = ${JSON.stringify(new Date().toISOString())};
export const peeringDbSource = "https://www.peeringdb.com/api/net";

export const peeringDbCounts = {
${counts.join("\n")}
} as const;

export const peeringDbNetworks: Record<string, readonly number[]> = {
${blocks.join("\n")}
};
`;
}

const grouped = new Map<NetworkType, number[]>();
for (const type of STORED_TYPES) grouped.set(type, []);
const seen = new Set<number>();

let skip = 0;
let pages = 0;
for (;;) {
  const rows = await fetchPage(skip);
  pages += 1;
  if (rows.length === 0) break;
  for (const row of rows) {
    if (typeof row.asn !== "number" || row.asn <= 0 || seen.has(row.asn)) continue;
    const networkType = networkTypeFromPeeringDb(row.info_types, row.info_type);
    if (!networkType) continue;
    seen.add(row.asn);
    grouped.get(networkType)?.push(row.asn);
  }
  console.error(`page ${pages}: +${rows.length} (classified ${seen.size})`);
  skip += rows.length;
  if (rows.length < PAGE) break;
  await sleep(400);
}

writeFileSync(OUTPUT, emit(grouped));
console.error(`wrote ${OUTPUT}`);
