import { integrationTool } from "./catalog";
import type { ProviderId } from "../revenue/types";

export function integrationCapabilities(provider: ProviderId): { features: string[]; scope: string } {
  const tool = integrationTool(provider)!;
  if (provider === "gong") return { features: ["Import transcripts, participants, timestamps, and recording links", "Bring in available briefs, highlights, Next Steps, topics, trackers, and speaker metrics", "Match Gong CRM references and participant emails to your connected CRM records", "Sync history and automatically coach imported calls"], scope: "Imports calls your Gong API credential can access. Private calls are excluded. Gong insight fields depend on your plan and availability; recordings open in Gong." };
  if (provider === "hubspot") return { features: ["Sync contacts, companies, deals, stages, owners, and pipeline values", "Match CRM records to call participants and link deals to conversations", "Send call summaries, coaching scores, next steps, and call links to deal or contact timelines", "Map coaching summary, score, next steps, and forecast category to deal or contact properties"], scope: "Notes and property updates are admin actions. Property updates run on review only after you map fields and opt in, or from an explicit update on the call. Repeated values are not sent again. Pipedrive and Attio keep notes only." };
  if (tool.category === "CRM") return { features: ["Sync contacts, companies, deals, stages, owners, and pipeline values", "Match CRM records to call participants and link deals to conversations", "Send call summaries, coaching scores, next steps, and call links to CRM timelines", "Optionally export calls when a manager marks them reviewed"], scope: "Exports create notes on linked records. Enable the required write permission in your CRM; automatic exports start after you opt in. CRM field edits and forecasting changes stay in your CRM." };
  if (tool.category === "Notifications") return { features: ["Share a call or coaching clip from its conversation", "Choose alerts for reviewed calls, new clips, and calls needing coaching", "Include coaching summaries and a direct link to the call", "Send a test message and track delivery"], scope: "Messages go to the channel selected by your incoming webhook. Viewing a call requires workspace access. Channel comments and commands are managed in your messaging app." };
  if (tool.category === "Automation") return { features: ["Receive completed calls and transcripts through an authenticated feed", "Send call summaries, next steps, coaching scores, and CRM context into an automation", "Trigger outbound workflows for newly imported or reviewed calls", "Track deliveries and use a stable event ID to prevent duplicates in your workflow"], scope: "Configure an outbound catch webhook to send events. Incoming feeds and outgoing workflows are configured separately. Outbound events include call details and summaries; transcript text is available through conversation export." };
  if (tool.category === "Meetings") return { features: ["Sync meeting times, organizers, attendees, meeting links, and cancellations", "Match scheduled meetings to call participants for context", "Import up to two years of meeting history", "Refresh automatically and reconnect when account permissions change"], scope: "Calendar sync supplies meeting context. Automatic meeting recording and email capture require a recording or mailbox integration; this calendar connection does not record meetings or read email." };
  if (tool.category === "Tasks") return { features: ["Sync tasks, statuses, assignees, deadlines, and links from your selected destination", "Turn an open coaching action item into a task", "Attach the source call link and track delivery", "Refresh task status automatically and prevent duplicate task exports"], scope: "Each connection uses one chosen project, board, database, list, or repository. Creating tasks requires write access. Remote completion is shown in the task workspace; coaching action completion is managed on the call." };
  return { features: ["Import completed transcripts with participant and recording context", "Keep provider timestamps and available summaries or next steps", "Match participants to connected CRM records", "Sync call history and optionally coach new calls automatically"], scope: "This connection imports available processed calls. Recording and transcription access depends on your provider account and plan. Open source recording links in the provider." };
}
